<a href="https://colab.research.google.com/github/jackiemacguire/learning-archive/blob/main/PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Tensors


Created using 'torch.Tensor()'

In [2]:
# @title Default title text
#scalar
scalar = torch.tensor(7)
scalar

#number of dimensions
scalar.ndim

#Get tensor back as Python int
scalar.item()

#Vector (magnitude and direction)
vector = torch.tensor([7,7])
vector

vector.ndim

vector.shape
torch.Size([2])

#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

MATRIX.ndim

MATRIX[1]

MATRIX.shape

#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,5,6],
                        [2,4,5]]])
TENSOR

TENSOR.ndim
TENSOR.shape
TENSOR[0]


#Random Tensors -> important because neural networks start learning
#with tensors full of random numbers and then adjust to better
#represent the data

#starts with random nums -> looks at data ->
#updates random nums -> looks at data -> updates random nums

#Create Random Tensor of size(3,4)
#https://docs.pytorch.org/docs/stable/generated/torch.rand.html
random_tensor = torch.rand(3,4)
random_tensor





tensor([[0.7917, 0.6678, 0.7520, 0.7440],
        [0.0516, 0.5040, 0.2135, 0.3548],
        [0.8176, 0.0619, 0.1527, 0.9147]])

In [3]:
random_tensor.ndim

#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))#height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [4]:
#Create a tensor of all 0's
zeros= torch.zeros(3,3)
zeros

#dtype stands for data type
zeros.dtype

random_tensor.dtype

torch.float32

In [5]:
#Creating a range of tensors and tensors-like
# use torch.arange()

one_to_twenty = torch.arange(1,21)
one_to_twenty
steps = torch.arange(start=0, end=200,step=8)
steps

#creating tensors like
twenty_zeros = torch.zeros_like(input=one_to_twenty)
twenty_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
#Tensor datatypes
# https://docs.pytorch.org/docs/stable/tensors.html
#Precision in Computing

#Float 32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor
                               device=None, #What device is tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations

float_32_tensor

#Getting info from Tensors
#to get datatype from tensor use tensor.dtype
#to get shape use tensor.shape
#to get device use tensor.device

#print to find details
print(f"datatype: {random_tensor.dtype}")



datatype: torch.float32


In [7]:
#Tensor Operations (addition, subtraction, multiplacation (element-wise) division. matrix multiplication)
tensor=torch.tensor([1,2,3])
tensor+20 #adds 20 to each value in []

tensor-50 #subtracts 50

tensor*2 #multiplies by 2

#Using PyTorch built-in functions
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [8]:
#Matrix Multiplication (dot product)

#Two main ways of multiplting in neural natworks and deep learning
  # element wise ie 2*[1,2,4]
  # matrix mult (or dot product) --> row x col and add up

#Element wise mult
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

#matrix mult
torch.matmul(tensor, tensor)


#Common errors in deep learning is shape error
#Two rules for matrix mult
#INNER dimensions must match :
# (3x2) and (3x2) won't work --> 2 and 3 don't match
# (3,2) and (2,3) will work --> 2 and 2 match

#The RESULTING matrix shape is the OUTER dimensions
# so the working example above resultant matrix will be 3x3

tensor_A = torch.tensor([[1,2],
                          [3,4],
                          [5,6]])
tensor_B = torch.tensor([[5,2],
                          [3,7],
                          [6,6]])
tensor_B, tensor_B.shape

tensor_B.T, tensor_B.T.shape


#This operation now works because tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
torch.matmul(tensor_A, tensor_B.T)
#To fix our tensor shape issues, we can manipulate the shape
#of one of our tensors using a TRANSPOSE--> switches the axes
#or dimensions of a given tensor


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])


tensor([[ 9, 17, 18],
        [23, 37, 42],
        [37, 57, 66]])

In [9]:
#Finding the min, max, mean, sum, etc (tensor aggregation)

# create a tensor
x= torch.arange(0,100,10)
x

#find max
torch.max(x), x.max()

# mean ** torch.mean() requires a tensor of float32 dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

#Finding positional min and max
# use argmin() for min ** it will return the index of the minimum
x.argmin()
#to get the specific value
x[0]

tensor(0)

In [10]:
# Reshaping, stacking, squeezing and unsqueezing tensors
# reshaping - reshapes an input tensor to a defined shape
# View - return a view of an input tensor of certain shapes but keeps the same memory as the og tensor
# stacking - combines multiple tensors on top of each other (vstack) or side by side (hstack)
# squeeze - removes all '1' dimensions from tensor
# unsqueeze - adds '1' dimension to a target tensor
# Permute - returns a view of the input with dimensions swapped in a certain way


x = torch.arange(1.,10.)
x, x.shape

# add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

# change view
z = x.view(1,9)
z, z.shape

# changing z changes x bc a view of a tensor shares the same memory as the og input
z[:, 0]=5
z,x

#Stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

# torch.squeeze() removes all single dimensions from a target tensor
x_reshaped.squeeze()

x_reshaped.squeeze().shape

x_squeezed = x_reshaped.squeeze()

# torch.unsqueeze()- adds a single dimension to a target tensor at a specific dim
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed)


#torch.permute() - rearrange dimensions

x_og = torch.rand(size=(224,224,3)) # heights width, color_channels

#permute the og tensor to rearrange the axis (or dim) order
x_permuted = x_og.permute(2,0,1) #shifts axis 0--> 1, 1-->2, 2-->0

x_og[0,0,0] = 728000
x_og[0,0,0], x_permuted[0,0,0]

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


(tensor(728000.), tensor(728000.))

In [11]:
#Selecting data from tensors (Indexing)

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

#Let's index on our new tensor
x[0]

#Let's index on the middle bracket (dim=1)
x[0][0]

#Let's index on the most inner (last dim)
x[0][1][1]

#You can also use ":" to select 'all' of a target dimension

x[:,0]

# Get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

#Get all the values of the 0 dim but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

#Get index 0 of 0th and 1st dimension and all values of 2nd dim
x[0, 0, :]

#Index on x to return last # in this matrix
print(x[0][2][2])

#Index on x to return last column
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


In [12]:
#PyTorch tensors and NumPy (numerical computing library)
#data in numpy, want in tensor --> torch.from_numpy(ndarray)
#PyTorch tensore -> numpy -> torch.Tensor.numpy()

import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #WARNING: converting from numpy-> pytorch, pytorch rejects numpy's default datatype of float64 unless specified
array, tensor

#tensor.dtype // what will happen to tensor if we change the value of array
array = array + 1

array, tensor

torch.arange(1.0, 8.0).dtype

#Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

numpy_tensor.dtype

#Change tensor, what happens to 'numpy_tensor'
tensor = tensor +1
tensor, numpy_tensor







(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [14]:
#Reproducbility (trying to take random out of random)

#to reduce randomness: Random seed --> it initializes the random number generator

random_tensor_A= torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


#random but redproducible tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

#REPRODUCIBILITY


tensor([[0.6189, 0.9531, 0.4133, 0.6765],
        [0.2546, 0.1429, 0.9983, 0.3258],
        [0.8146, 0.7345, 0.7681, 0.4564]])
tensor([[0.7052, 0.9378, 0.0813, 0.5049],
        [0.2976, 0.5322, 0.5927, 0.6138],
        [0.1362, 0.8695, 0.5829, 0.5610]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
#Running tensors and PyTorch objects on the GPUs (and making them faster computations)
#GPUs = faster computation on numbers thanks to CUDA and NVIDIA hardware
# can use google colab, colab pro, or buy your own, or cloud computing like AWS, Azure

# GPU access
torch.cuda.is_available()

#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

#count num of devices
torch.cuda.device_count()

#Putting tensors / models on gpu is bc it results in faster computations
#Create a tensor (default in cpu)
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensore.device)

#move tensor to gpu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.numpy()
#if tensor is on gpu, cant transform it to NumPy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu
tensor_on_gpu
